<?php require 'templates/header.phtml' ?>
<div class="colorFondo">
    <h1>Selecione una Cepa para buscar nuestra lista de vinos</h2>

        <ul>
            <table class="table table-success table-striped">
                <?php foreach ($cepas as $cepa) : ?>
                    <tr>
                        <td class="table-secondary"> <a href="mostrarVinosPorCepa/<?= $cepa->id_cepa ?>"><?= $cepa->Nombre_cepa ?></a></td>
                    </tr>
                <?php endforeach ?>
            </table>

        </ul>
</div>
<?php require 'templates/footer.phtml' ?>