<?php require 'templates/header.phtml' ?>
<div class="colorFondo">
<div class="formularioRegistro">
    <div class="mt-5 w-25 mx-auto">
        <form method="POST" action="auth">
            <div class="form-group">
                <label for="text">Email</label>
                <input type="text" required class="form-control" id="email" name="email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" required class="form-control" id="password" name="password">
            </div>

            <?php if ($error) : ?>
                <div class='alert alert-danger' role='alert'>
                    <?= $error ?>
                </div>
            <?php endif ?>

            <button type="submit" class="btn btn-primary mt-3">Entrar</button>
        </form>
    </div>
</div>
</div>

<?php require 'templates/footer.phtml' ?>