</main>
<!-- fin main container -->

<!-- main footer -->
<footer class="d-flex flex-wrap flex-direction-row justify-content-center align-items-center py-3 my-4 border-top">

        <div class="align-items-center">
                <span class="text-muted">VINOTECA TANDIL</span>
        </div>
        <div class="redes-sociales">
                <div class="instagram">
                        <a href="https://www.instagram.com/" target="_blank">
                                Instagram</a>
                </div>
                <div class="facebook">
                        <a href="https://www.facebook.com/" target="_blank">
                                Facebook</a>
                </div>
        </div>

</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>