<!DOCTYPE html>
<html lang="en">

<head>

    <base href="<?= BASE_URL ?>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Vinoteca tandil</title>
</head>

<header>
    <h1>VINOTECA TANDIL</h1>
<nav>
    <div class="container text-center">
        <div class="row align-items-center">
        <div class="col">
                <label class="btn btn-secondary" for="option2"><a href="home">home</a></li>  </label>
            </div>
            <div class="col">
                <label class="btn btn-secondary" for="option2"><a href="listar">Vinos</a></label>
            </div>
            <div class="col">
                <label class="btn btn-secondary" for="option2"><a href="mostrarCepas">Cepas</a></label>
            </div>
            <div class="col">
                <label class="btn btn-secondary" for="option2"><a href="buscarVinosPorCepa">Buscar por Cepas</a></label>
            </div>
            <?php if (!isset($_SESSION['USER_ID'])) : ?>
            <div class="col">
                <label class="btn btn-secondary" for="option2"><a href="login">Login</a></label>
            </div>
            <?php else : ?>
            <div class="col">
                <label class="btn btn-secondary" for="option2"><a href="logout">Logout (<?= $_SESSION['USER_EMAIL'] ?>)</a></label>
            </div>
            <?php endif ?>
        </div>
    </div>
</nav>
</header>
