<?php require 'templates/header.phtml' ?>


<section class="descripcion">
        <div class="vinoteca">
            <h2> Vinoteca y selección de vinos</h2>
            <p>Detrás de una vinoteca hay un sommelier especializado que está ansioso por ayudarte a conocer todo sobre los vinos, que se convierte en un amigo, 
                que sabe que te llevaste la semana anterior, o con quien lo compartiste, o con que lo vas a maridar
                En este sentido deseamos ofrecer a partir de nuestra pagina consejos de maridaje según la cepa que 
                compone al vino, e información.
                Es por ello que ofrecemos un listado de nuestros vinos seleccionados y sus caracteristicas. 
            </p>
        </div>
</section>

<section class="descripcion">
        <div class="cepas">
            <h2>Nuestra Seleccion de cepas</h2>
            <p>Las cepas son las diferentes variedades de vides que producen diversos tipos de uvas con características 
               diferenciadoras. Estas pueden localizarse en ámbitos geográficos concretos, aunque gracias a las técnicas 
               de viticultura se van extendiendo, y se reproducen mediante esquejes, injertos y acodos.
               Es por ello que compartimos con ustedes en este sitio nuestra seleccion de cepas, los vinos asociadas a ellas,
               y una breve descripción de las mismas! Esperamos que disfruten de esta información!
            </p>
        </div>
</section>


<?php require 'templates/footer.phtml' ?>

