<?php require 'templates/header.phtml' ?>
<div class="colorFondo">
<h1>Vinos por cepa: <?= $cepa->Nombre_cepa ?></h1>
    <table class="table table-success table-striped">
        <td class="table-secondary">Vino</td>
        <td class="table-secondary">Bodega</td>
        <?php foreach ($vinos as $vino) : ?>
            <tr>
                <td class="table-secondary"><a href="mostrarVino/<?= $vino->ID_vino ?>"> <?= $vino->Nombre ?> </a></td>
                <td class="table-secondary"><a href="mostrarBodega/<?= $vino->id_bodega ?>"><?= $vino->Nombre_bodega ?></a></td>
            </tr>
        <?php endforeach ?>
    </table>
</ul>
</div>
<?php require 'templates/footer.phtml' ?>